
name: Deploy Static Website to ECS # 工作流名称

on:
  push:
    # 每次推送到 main 分支时触发自动化
    branches:
      - main
  workflow_dispatch: # 允许手动点击运行

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        # 使用标准的 GitHub 官方 Action
        uses: actions/checkout@v4

      - name: Deploy via SSH
        # 使用 appleboy/ssh-action 来处理 SSH 连接和 rsync 文件同步
        uses: appleboy/ssh-action@v1.0.3

        # 关键部分：确保 'with:' 和上面的 'uses' 处于同级缩进
        with:
          # 以下参数都必须在 'with:' 下，并使用相同的缩进（通常是四个空格）
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}

          # 核心部署命令
          script: |
            echo "--- Starting Deployment ---"
            
            # 1. 确保服务器有 rsync 
            sudo apt update && sudo apt install rsync -y
            
            # 2. ⚠️ 关键修改：只同步 $GITHUB_WORKSPACE/docs/ 目录下的内容
        # 注意：最后要加 / 以同步目录内容而不是目录本身
            rsync -avz --delete $GITHUB_WORKSPACE/docs/ /var/www/docs/
            
            echo "Deployment finished successfully."